include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable additional useful rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    avoid_unnecessary_containers: true
    prefer_collection_literals: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"