name: fit_mobile_app
description: FIT Mobile App for international touch events
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  xml: ^6.5.0
  visibility_detector: ^0.4.0+2
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  # shared_preferences: ^2.4.0  # Temporarily disabled for Android build testing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true